openapi: "3.0.3"
info:
  title: "Delta API"
  description: "API for Delta"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
  - url: "http://delta-backend"
paths:
  /admin/events:
    get:
      tags:
        - admin
      description: "Get all events created by me"
      operationId: getMyEvents
      responses:
        "200":
          description: "All my events"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"
    put:
      tags:
        - admin
      description: "Create an event"
      operationId: createEvent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEvent'
      responses:
        "201":
          description: "created event"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
  /event:
    get:
      tags:
        - user
      description: "Get future events"
      operationId: getFutureEvents
      responses:
        "200":
          description: "All future events"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"
  /event/{id}:
    get:
      tags:
        - user
      description: "Get an event"
      operationId: getEvent
      parameters:
        - name: id
          in: path
          description: "Event id"
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"
      responses:
        "201":
          description: "Event joined"
    put:
      tags:
        - user
      description: "Join an event"
      operationId: joinEvent
      parameters:
        - name: id
          in: path
          description: "Event id"
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JoinEvent"
      responses:
        "201":
          description: "Event joined"
    delete:
      tags:
        - user
      description: "Leave an event"
      operationId: leaveEvent
      parameters:
        - name: id
          in: path
          description: "Event id"
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LeaveEvent"
      responses:
        "200":
          description: "Event left"
components:
  schemas:
    CreateEvent:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        location:
          type: string
    Event:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        location:
          type: string
        ownerEmail:
          type: string
        id:
          type: string
          format: uuid
    JoinEvent:
      type: object
      properties:
        email:
          type: string
          format: email
    LeaveEvent:
      properties:
        otp:
          type: string
          format: uuid
