apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: delta-backend
  namespace: delta
  labels:
    team: delta
spec:
  image: {{image}}
  ingresses:
    - https://delta-backend.ekstern.dev.nav.no
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: delta
