apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: delta-backend
  namespace: delta
  labels:
    team: delta
spec:
  image: {{image}}
  ingresses:
    - https://delta-backend.intern.dev.nav.no
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: delta
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
